### ISSUE TITLE
onReady is not a function

### ISSUE THREAD

**Issue by grigoreo-fox** [thekip/node-modbus-rtu#1]
I'm trying to run demo
`var SerialPort = require('serialport').SerialPort;
var serialPort = new SerialPort("/dev/ttyUSB0", { baudrate: 19200 });
var modbus = require('modbus-rtu');

//create ModbusMaster instance and pass the serial port object
var master = new modbus.Master(serialPort);
`

And get an error

> TypeError: onReady is not a function
>     at /home/pi/mb_test/node_modules/modbus-rtu/master.js:16:9
>     at SerialPort.<anonymous> (/home/pi/mb_test/node_modules/modbus-rtu/serial-helper.js:33:13)
>     at emitNone (events.js:67:13)
>     at SerialPort.emit (events.js:166:7)
>     at SerialPort.<anonymous> (/home/pi/mb_test/node_modules/serialport/lib/serialport.js:226:10)

**Comment by timofei-iatsenko** [comment]
looks like npm has an outdate version. 

I'll check it.

**Comment by timofei-iatsenko** [comment]
Have updated npm registry. Install 0.0.2 version, and try it again.

**Comment by grigoreo-fox** [comment]
Yes, now it works!
But seems, that bluebird is missing in package file...
