### ISSUE TITLE
Version 0.1.x fails with Error "TypeError: Object ï¿½D has no method 'equals' " in node.js 0.10.29

### ISSUE THREAD

**Issue by milen100** [thekip/node-modbus-rtu#4]
I guess it means that users with node.js 0.10.x should use version 0.0.2. of this lib .
I'm not users this is an real issue, but just wanted to add a warning(an save some time debugging) in case others users have the same error.

**Comment by timofei-iatsenko** [comment]
Sorry for later answer. 
Whe i added breaking changes i also added a engines restriction in package.json (see this commit https://github.com/thekip/node-modbus-rtu/commit/fd373263983c8f09474f011b00758b9fa07ab25c). So npm should warn you about node version incompatibility. 

But may be add it to readme is good thing.

**Comment by milen100** [comment]
Yes, mention in readme+ visible warning  file should be ok. Thank you
