### ISSUE TITLE
TimeoutError: Response timeout exceed!

### ISSUE THREAD

**Issue by naveen26246** [thekip/node-modbus-rtu#6]
I am getting the following error while testing a sample modbus connection on ubuntu16.04. 

**TimeoutError: Response timeout exceed!**

Any tips to debug the issue ?

**Comment by timofei-iatsenko** [comment]
Try to increase response timeout may be it helps. 

Also you can get familiar yourself with this timeouts: https://github.com/thekip/node-modbus-rtu/issues/5

Also you can enable debug mode by passing `{ debug: true }` to constructor: 

```js
var master = new modbus.Master(serialPort, {debug: true});
```
And watching what exactly sent/received to serial port.

But actually, looks like you don't have connection to your modbus device. Check serial port number (or device if you on *nix system), check physical connection, slave adres and etc.

**Comment by naveen26246** [comment]
Hi, as suggested, I have run it in the debug mode. Here is the output: 

write <Buffer 01 03 00 5e 00 02 a5 d9>
resp <Buffer 01 03 00 5e 00 02 a5 d9>
[RangeError: index out of range]

Any particular issue I need to look into ?

**Comment by timofei-iatsenko** [comment]
Looks like your device responds with incorrect packet, it's just bounce received request.

But in actual modbus it should return "Respond packet",  and have to be something like that: 
```
<Buffer 01 03 04 00 00 00 00 a5 d9>
```
check this [document](http://www.modbustools.com/modbus.html#function03) to get more about modbus protocol specification

**Comment by naveen26246** [comment]
@thekip ..as you suggested, the issue was with my device. Found the fix. Thanks.
